Update README.md
calvh/mlh-final-project pull request #56
Opened 2021-08-07 01:53 UTC by nimra200

Add instructions on how to get the site running.

2021-08-07 21:04 UTC, calvh requested changes
Thanks for doing this @nimra200 

I just have a minor comment about the requirements 

Also for next time, please try to prefix your branch name with a number (I recommend using the issue number) to keep branches unique and prevent conflicts (imagine if someone else also used the branch name "readme-installation")

so you can use something like 34-readme-installation

To get the number, just create a new issue.

2021-08-07 21:04 UTC, calvh commented on README.md
> +
I recommend having `pip install -r requirements.txt` instead of installing packages separately

2021-08-08 00:28 UTC, calvh commented
@nimra200 Could you also please change the title from "Installation" to "Flask Development Installation"

I have found that setting the following environment variables in an `.env` file at the root of the `flask` folder (without adding python-dotenv package) works for me. If you could, please try replicating that and see if the app works on your end. If it does, then you can add that instruction to the list of steps.

```
FLASK_ENV
SECRET_KEY
MONGO_USER
MONGO_PASSWORD
DB
AUTH_SOURCE
HOSTNAME
PORT
```

@Rebecca-CYLi @HamdiaA appreciate if you could also confirm the above

2021-08-10 19:26 UTC, Rebecca-CYLi submitted a review, later dismissed
good!

2021-08-10 23:48 UTC, calvh commented
Might as well add tick the checkboxes to the requirements we have satisfied so far

2021-08-11 17:15 UTC, calvh commented
Please see #105 and update accordingly

2021-08-11 17:46 UTC, calvh commented
Add these to the top of the README right after the top-level header to include badges

![License](https://img.shields.io/github/license/calvh/mlh-final-project)
![Open Issues](https://img.shields.io/github/issues-raw/calvh/mlh-final-project)
![Closed Issues](https://img.shields.io/github/issues-closed-raw/calvh/mlh-final-project)
![Open PRs](https://img.shields.io/github/issues-pr-raw/calvh/mlh-final-project)
![Closed PRs](https://img.shields.io/github/issues-pr-closed-raw/calvh/mlh-final-project)

Including this will fix #7

2021-08-15 17:54 UTC, Rebecca-CYLi approved these changes
wait, his latest review says "the readme is to describe the project". we need to change it to make sure the user knows what its doing

2021-08-15 17:56 UTC, Rebecca-CYLi requested changes
wait, his latest review says "the readme is to describe the project". we need to change it to make sure the user knows what its doing

2021-08-15 18:27 UTC, Rebecca-CYLi commented
Ok, I added the description. New Review needed

2021-08-15 23:55 UTC, calvh commented
Thanks @Rebecca-CYLi. The numbered lists don't display properly so I am fixing them now.

2021-08-16 23:42 UTC, calvh approved these changes

2021-08-16 23:43 UTC, merged