Change color scheme
calvh/mlh-final-project pull request #64
Opened 2021-08-08 20:12 UTC by nimra200

Linked to #10 

Changed the colors for index, play, login and registration pages. The main colors are orange and brown.

I tried to move the styles on the login and registration html pages to the CSS file, but they were not showing up. Also, the copyright logo appears differently on the login and register pages. I am not sure why this is happening.

2021-08-09 02:12 UTC, calvh commented on flask/app/static/styles/index.css
> +.mt-auto {
I would recommend not linking custom styles to a Bootstrap class because you might want to use `mt-auto` elsewhere without the styles specified here.

2021-08-09 02:14 UTC, calvh commented
> Also, the copyright logo appears differently on the login and register pages. I am not sure why this is happening.

Do you have screenshots?

2021-08-09 02:19 UTC, calvh requested changes
My only comment is on the `mt-auto` and I prefer to see it changed to prevent conflicts.

Additionally, I suggest separating `index.css` into multiple files, separated by page, but that should be done in another issue

2021-08-09 02:25 UTC, nimra200 commented
Thanks Calvin for reviewing my PR. I'll remove the styling from mt-auto as you've suggested.

2021-08-09 02:27 UTC, nimra200 commented
> > Also, the copyright logo appears differently on the login and register pages. I am not sure why this is happening.
> 
> Do you have screenshots?
![Screen Shot 2021-08-08 at 10 23 16 PM](https://user-images.githubusercontent.com/56455442/128654680-aff81a11-9a6c-43e5-a7a6-3023c5b950e2.png)
![Screen Shot 2021-08-08 at 10 21 31 PM](https://user-images.githubusercontent.com/56455442/128654691-99b51ad7-a680-486e-be1f-1876e93e2935.png)

2021-08-09 16:35 UTC, nimra200 commented
Removed the custom style from `mt-auto`.

2021-08-09 22:06 UTC, calvh approved these changes
lgtm

2021-08-09 23:14 UTC, Rebecca-CYLi commented
The login page is off-centered compared to the register page, does it look different for anyone else?

2021-08-10 02:33 UTC, nimra200 commented
@Rebecca-CYLi Seemed fine for me. Can you put a screenshot of what you see?

2021-08-10 02:42 UTC, Rebecca-CYLi commented
<img width="1680" alt="Screen Shot 2021-08-09 at 10 41 13 PM" src="https://user-images.githubusercontent.com/48325436/128800207-e03e2f5e-f3c9-4f3c-97db-75a330dfd6b1.png">
<img width="1680" alt="Screen Shot 2021-08-09 at 10 41 09 PM" src="https://user-images.githubusercontent.com/48325436/128800211-f0b817d4-e1e7-4965-8aeb-1ae17703676d.png">

2021-08-10 02:50 UTC, nimra200 commented
@Rebecca-CYLi  I see what you mean. I'll try to fix it right now.

2021-08-10 03:08 UTC, nimra200 commented
The login and register pages look centered now. This also fixes the problem in #71.

2021-08-10 03:09 UTC, Rebecca-CYLi approved these changes
Looks good!

2021-08-10 03:10 UTC, merged

2021-08-10 03:43 UTC, calvh commented
@nimra200 awesome work